#!/bin/bash
# ============================================
# hourly-update.sh - Hourly Automation Script
# Runs every hour to refresh data and log metrics
# ============================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_DIR="/root/.openclaw/workspace"
MEMORY_DIR="$WORKSPACE_DIR/memory"
LOG_FILE="$MEMORY_DIR/hourly-update.log"

# Timestamps
TIMESTAMP=$(date -u +"%Y-%m-%d %H:%M UTC")
HOUR=$(date -u +"%H")

log() {
    echo "[$TIMESTAMP] $1" | tee -a "$LOG_FILE"
}

log "========== HOURLY UPDATE STARTED =========="

# 1. Refresh dashboard data
log "Step 1: Refreshing dashboard data..."
cd "$WORKSPACE_DIR/dashboard-athena"
npm run build > /dev/null 2>&1 || log "Warning: Dashboard build had issues (may be normal)"
log "Dashboard rebuild completed"

# 2. Check Beelancer status
log "Step 2: Checking Beelancer status..."
BEELANCER_STATE="$MEMORY_DIR/beelancer-state.json"
if [ -f "$BEELANCER_STATE" ]; then
    LAST_POLL=$(grep -o '"last_poll"[^,]*' "$BEELANCER_STATE" | head -1 || echo "last_poll: unknown")
    PENDING_BIDS=$(grep -o '"pending_bids"[^,]*' "$BEELANCER_STATE" | head -1 || echo "pending_bids: unknown")
    ACTIVE_GIGS=$(grep -o '"active_gigs"[^,]*' "$BEELANCER_STATE" | head -1 || echo "active_gigs: 0")
    log "Beelancer status: $ACTIVE_GIGS, $PENDING_BIDS"
else
    log "Warning: beelancer-state.json not found"
fi

# Also check bid-monitor-log if exists
BID_MONITOR="$MEMORY_DIR/bid-monitor-log.json"
if [ -f "$BID_MONITOR" ]; then
    log "Bid monitor log exists - checking recent activity"
fi

# 3. Log system metrics
log "Step 3: Logging system metrics..."

# CPU load
CPU_LOAD=$(uptime | awk -F'load average:' '{print $2}' | awk '{print $1}' | tr -d ',')

# Memory usage
MEM_TOTAL=$(free -h | awk '/^Mem:/ {print $2}')
MEM_USED=$(free -h | awk '/^Mem:/ {print $3}')
MEM_PERCENT=$(free | awk '/^Mem:/ {printf "%.0f", $3/$2 * 100}')

# Disk usage
DISK_USAGE=$(df -h "$WORKSPACE_DIR" | awk 'NR==2 {print $5}' | tr -d '%')

# OpenClaw process check
OPENCLAW_PROCS=$(ps aux | grep -i openclaw | grep -v grep | wc -l)

# Git status check
cd "$WORKSPACE_DIR"
GIT_STATUS=$(git status --porcelain 2>/dev/null | wc -l || echo "0")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

log "System Metrics:"
log "  - CPU Load (1m): $CPU_LOAD"
log "  - Memory: $MEM_USED / $MEM_TOTAL ($MEM_PERCENT%)"
log "  - Disk Usage: $DISK_USAGE%"
log "  - OpenClaw Processes: $OPENCLAW_PROCS"
log "  - Git pending changes: $GIT_STATUS on branch $GIT_BRANCH"

# 4. Commit changes to git (if any)
log "Step 4: Checking git changes..."
if [ "$GIT_STATUS" -gt "0" ]; then
    log "Found $GIT_STATUS uncommitted changes - committing..."
    git add -A
    git commit -m "Hourly update: $TIMESTAMP
- System: CPU=$CPU_LOAD Mem=$MEM_PERCENT% Disk=$DISK_USAGE%
- Beelancer: $ACTIVE_GIGS $PENDING_BIDS
- Auto-generated by hourly-update.sh" || log "Git commit failed (may be no changes)"
    log "Changes committed"
else
    log "No changes to commit"
fi

log "========== HOURLY UPDATE COMPLETED =========="
log ""

# Keep last 7 days of logs
find "$MEMORY_DIR" -name "hourly-update.log" -mtime +7d -delete 2>/dev/null || true

exit 0
